spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dslist
    username: postgres
    password: 1234567

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

#      jakarta:       #### fica entre o properties e o hibernate ####
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
